#!/bin/bash

cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p455_pres_101219_interpolated_arrays_density_M2p455_T250p0_P101219p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p455_pres_101219_interpolated_arrays_density_M2p455_T275p0_P101219p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p455_pres_101219_interpolated_arrays_density_M2p455_T300p0_P101219p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p477_pres_96187_interpolated_arrays_density_M2p477_T250p0_P96187p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p477_pres_96187_interpolated_arrays_density_M2p477_T275p0_P96187p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p477_pres_96187_interpolated_arrays_density_M2p477_T300p0_P96187p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p47_pres_150690_interpolated_arrays_density_M2p470_T250p0_P150690p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p47_pres_150690_interpolated_arrays_density_M2p470_T275p0_P150690p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p47_pres_150690_interpolated_arrays_density_M2p470_T300p0_P150690p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p608_pres_177755_interpolated_arrays_density_M2p608_T250p0_P177755p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p608_pres_177755_interpolated_arrays_density_M2p608_T275p0_P177755p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p608_pres_177755_interpolated_arrays_density_M2p608_T300p0_P177755p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p649_pres_170657_interpolated_arrays_density_M2p649_T250p0_P170657p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p649_pres_170657_interpolated_arrays_density_M2p649_T275p0_P170657p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p649_pres_170657_interpolated_arrays_density_M2p649_T300p0_P170657p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p827_pres_136743_interpolated_arrays_density_M2p827_T250p0_P136743p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p827_pres_136743_interpolated_arrays_density_M2p827_T275p0_P136743p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_2p827_pres_136743_interpolated_arrays_density_M2p827_T300p0_P136743p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_3p143_pres_125750_interpolated_arrays_density_M3p143_T250p0_P125750p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_3p143_pres_125750_interpolated_arrays_density_M3p143_T275p0_P125750p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_3p143_pres_125750_interpolated_arrays_density_M3p143_T300p0_P125750p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_3p17_pres_147136_interpolated_arrays_density_M3p170_T250p0_P147136p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_3p17_pres_147136_interpolated_arrays_density_M3p170_T275p0_P147136p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_3p17_pres_147136_interpolated_arrays_density_M3p170_T300p0_P147136p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_4p341_pres_142725_interpolated_arrays_density_M4p341_T250p0_P142725p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_4p341_pres_142725_interpolated_arrays_density_M4p341_T275p0_P142725p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_4p341_pres_142725_interpolated_arrays_density_M4p341_T300p0_P142725p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_5p085_pres_140813_interpolated_arrays_density_M5p085_T250p0_P140813p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_5p085_pres_140813_interpolated_arrays_density_M5p085_T275p0_P140813p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_5p085_pres_140813_interpolated_arrays_density_M5p085_T300p0_P140813p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_5p408_pres_170841_interpolated_arrays_density_M5p408_T250p0_P170841p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_5p408_pres_170841_interpolated_arrays_density_M5p408_T275p0_P170841p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_5p408_pres_170841_interpolated_arrays_density_M5p408_T300p0_P170841p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_5p898_pres_170272_interpolated_arrays_density_M5p898_T250p0_P170272p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_5p898_pres_170272_interpolated_arrays_density_M5p898_T275p0_P170272p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_5p898_pres_170272_interpolated_arrays_density_M5p898_T300p0_P170272p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_5p956_pres_151548_interpolated_arrays_density_M5p956_T250p0_P151548p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_5p956_pres_151548_interpolated_arrays_density_M5p956_T275p0_P151548p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_5p956_pres_151548_interpolated_arrays_density_M5p956_T300p0_P151548p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_6p184_pres_104778_interpolated_arrays_density_M6p184_T250p0_P104778p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_6p184_pres_104778_interpolated_arrays_density_M6p184_T275p0_P104778p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_6p184_pres_104778_interpolated_arrays_density_M6p184_T300p0_P104778p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_6p396_pres_130039_interpolated_arrays_density_M6p396_T250p0_P130039p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_6p396_pres_130039_interpolated_arrays_density_M6p396_T275p0_P130039p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_6p396_pres_130039_interpolated_arrays_density_M6p396_T300p0_P130039p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_6p535_pres_96501_interpolated_arrays_density_M6p535_T250p0_P96501p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_6p535_pres_96501_interpolated_arrays_density_M6p535_T275p0_P96501p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_6p535_pres_96501_interpolated_arrays_density_M6p535_T300p0_P96501p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_6p605_pres_192094_interpolated_arrays_density_M6p605_T250p0_P192094p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_6p605_pres_192094_interpolated_arrays_density_M6p605_T275p0_P192094p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_6p605_pres_192094_interpolated_arrays_density_M6p605_T300p0_P192094p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_6p981_pres_178764_interpolated_arrays_density_M6p981_T250p0_P178764p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_6p981_pres_178764_interpolated_arrays_density_M6p981_T275p0_P178764p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_6p981_pres_178764_interpolated_arrays_density_M6p981_T300p0_P178764p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_7p037_pres_107813_interpolated_arrays_density_M7p037_T250p0_P107813p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_7p037_pres_107813_interpolated_arrays_density_M7p037_T275p0_P107813p0
sbatch submit.slurm
cd - > /dev/null
cd ./double_ramp_configuration/outputs/backward/sweep/double_ramp_0p046_0p0112_ma_7p037_pres_107813_interpolated_arrays_density_M7p037_T300p0_P107813p0
sbatch submit.slurm
cd - > /dev/null
