#!/usr/bin/env python3
"""
Generate double ramp 2D meshes using Gmsh and export in SU2 format.

Features:
- Parameterized number of samples (default 200)
- Random sampling of y_ramp_1 and y_ramp_2 with controlled offset
- Deterministic option via --seed
- Output directory management and safety checks
- Skips regeneration of existing meshes unless --overwrite specified
- Graceful error handling and summary report

Example:
    python generate_double_ramp_meshes.py \
        --n 300 \
        --y1-min 0.01 --y1-max 0.05 \
        --delta 0.04 \
        --out-dir double_ramps_200 \
        --gmsh gmsh

Author: Auto-generated by assistant
"""
from __future__ import annotations

import argparse
import random
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import List


@dataclass
class RampSample:
    y1: float
    y2: float
    geo_path: Path
    su2_path: Path
    generated: bool = False
    skipped: bool = False
    error: str | None = None


def sample_pair(rng: random.Random, y1_min: float, y1_max: float, delta: float, precision: int = 4) -> tuple[float, float]:
    y1 = round(rng.uniform(y1_min, y1_max), precision)
    lower_y2 = max(0.0, y1 - delta)
    upper_y2 = y1 + delta
    y2 = round(rng.uniform(lower_y2, upper_y2), precision)
    return y1, y2


GEO_TEMPLATE = """SetFactory(\"OpenCASCADE\");
Point(1) = {0.08, 0, 0, 1.0};
Point(2) = {0.1, 0, 0, 1.0};
Point(3) = {0.2, {y1}, 0, 1.0};
Point(4) = {0.3, {y1}, 0, 1.0};
Point(5) = {0.4, {y2}, 0, 1.0};
Point(6) = {0.7, {y2}, 0, 1.0};
Point(7) = {0.7, 0.4, 0, 1.0};
Point(8) = {0.08, 0.4, 0, 1.0};
Line(1) = {1, 2};
Line(2) = {2, 3};
Line(3) = {3, 4};
Line(4) = {4, 5};
Line(5) = {5, 6};
Line(6) = {6, 7};
Line(7) = {7, 8};
Line(8) = {8, 1};
Curve Loop(1) = {7, 8, 1, 2, 3, 4, 5, 6};
Plane Surface(1) = {1};
Physical Curve(\"Inlet\", 9) = {8};
Physical Curve(\"Outlet\", 10) = {6};
Physical Curve(\"Wall\", 11) = {7, 1, 2, 3, 4, 5};
Physical Surface(\"Fluid\", 12) = {1};
Transfinite Surface {1} = {8, 7, 6, 1};
Transfinite Curve {8, 6} = 201 Using Progression 1;
Transfinite Curve {2, 3, 4} = 51 Using Progression 1;
Transfinite Curve {1} = 11 Using Progression 1;
Transfinite Curve {5} = 151 Using Progression 1;
Transfinite Curve {7} = 311 Using Progression 1;
Recombine Surface {1};
"""


def write_geo(path: Path, y1: float, y2: float) -> None:
    path.write_text(GEO_TEMPLATE.format(y1=y1, y2=y2))


def run_gmsh(gmsh_cmd: str, geo: Path, su2: Path, dim: int = 2) -> subprocess.CompletedProcess:
    cmd = [gmsh_cmd, str(geo), f"-{dim}", "-o", str(su2)]
    return subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)


def generate(args: argparse.Namespace) -> List[RampSample]:
    out_dir = Path(args.out_dir)
    geo_dir = out_dir / "geo_files"
    su2_dir = out_dir / "su2_meshes"

    for d in (out_dir, geo_dir, su2_dir):
        d.mkdir(parents=True, exist_ok=True)

    rng = random.Random(args.seed)

    samples: List[RampSample] = []
    for _ in range(args.n):
        y1, y2 = sample_pair(rng, args.y1_min, args.y1_max, args.delta, args.precision)
        geo_name = f"double_ramp_{y1}_{y2}.geo"
        su2_name = f"double_ramp_{y1}_{y2}.su2"
        geo_path = geo_dir / geo_name
        su2_path = su2_dir / su2_name
        sample = RampSample(y1, y2, geo_path, su2_path)

        if su2_path.exists() and not args.overwrite:
            sample.skipped = True
            samples.append(sample)
            continue

        # Write .geo
        write_geo(geo_path, y1, y2)
        # Invoke gmsh
        proc = run_gmsh(args.gmsh, geo_path, su2_path, dim=args.dim)
        if proc.returncode != 0 or not su2_path.exists():
            sample.error = f"gmsh failed (code={proc.returncode}) stderr: {proc.stderr.strip()}"
        else:
            sample.generated = True
        samples.append(sample)

    return samples


def summarize(samples: List[RampSample]) -> str:
    gen = sum(1 for s in samples if s.generated)
    skip = sum(1 for s in samples if s.skipped)
    err = sum(1 for s in samples if s.error and not s.generated)
    unique_pairs = {(s.y1, s.y2) for s in samples}
    lines = [
        "Generation summary:",
        f"  Total requested: {len(samples)}",
        f"  Unique parameter pairs: {len(unique_pairs)}",
        f"  Generated: {gen}",
        f"  Skipped (existing): {skip}",
        f"  Errors: {err}",
    ]
    if err:
        lines.append("  Error details (first 5):")
        for s in [s for s in samples if s.error][:5]:
            lines.append(f"    y1={s.y1} y2={s.y2}: {s.error}")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate parametric double ramp meshes in SU2 format using Gmsh.")
    p.add_argument('-n', '--n', type=int, default=200, help='Number of random samples to generate (default: 200)')
    p.add_argument('--y1-min', type=float, default=0.01, help='Lower bound for y_ramp_1 (default: 0.01)')
    p.add_argument('--y1-max', type=float, default=0.05, help='Upper bound for y_ramp_1 (default: 0.05)')
    p.add_argument('--delta', type=float, default=0.04, help='Max |y2 - y1| bound (default: 0.04)')
    p.add_argument('--precision', type=int, default=4, help='Decimal precision for rounding (default: 4)')
    p.add_argument('--gmsh', type=str, default='gmsh', help='Gmsh executable or path (default: gmsh in PATH)')
    p.add_argument('--out-dir', type=str, default='double_ramps_200', help='Output directory root (default: double_ramps_200)')
    p.add_argument('--dim', type=int, default=2, choices=[2,3], help='Mesh dimension for Gmsh (default: 2)')
    p.add_argument('--seed', type=int, default=None, help='Random seed for reproducibility (default: None)')
    p.add_argument('--overwrite', action='store_true', help='Overwrite existing meshes instead of skipping')
    return p.parse_args()


def main():
    args = parse_args()

    if args.y1_min >= args.y1_max:
        raise SystemExit("--y1-min must be < --y1-max")
    if args.delta <= 0:
        raise SystemExit("--delta must be positive")
    if args.precision < 1 or args.precision > 8:
        raise SystemExit("--precision out of reasonable range (1-8)")

    samples = generate(args)
    print(summarize(samples))


if __name__ == '__main__':
    main()
